# Generated by Django 3.2 on 2021-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specialization', models.TextField()),
                ('bio', models.TextField()),
                ('qualification', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=120)),
                ('hospital', models.CharField(max_length=120)),
                ('languages', models.CharField(max_length=120)),
                ('job_type', models.CharField(max_length=120)),
                ('contact1', models.IntegerField()),
                ('contact2', models.IntegerField()),
                ('email1', models.CharField(max_length=120)),
                ('email2', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
